### ISSUE TITLE
Python Script Error PyOpenMS ExtractionCoordinates in Extract feature peaks from samples 

### ISSUE THREAD

**Issue by fejacko** [alexandrovteam/LCMS#13]
Hi, 

I've been trying to analyze some .mzXML files with Optimus but keep getting stuck.

I've narrowed the source of the error down to the "Extract feature peaks from samples" Python Script node ("Align and quantify features" metanode --> "Save features to session storage" metanode --> "Extract feature peaks from samples" Python Script node). It seems to stem from PyOpenMS ExtractionCoordinates but I can't find any documentation on what would cause this error. 

Both the Standard Output and the Error Output are empty.

This is the error I keep getting (this is just the beginning of it, it goes on for many more objects):

```
ERROR Python Script (1⇒1)  0:413:406:349 ordinates object at 0x7fdeeb730290>, <pyopenms.pyopenms_7.ExtractionCoordinates object at 0x7fdeeb730850>, <pyopenms.pyopenms_7.ExtractionCoordinates object at 0x7fdeec6a6950>, <pyopenms.pyopenms_7.ExtractionCoordinates object at 0x7fdeec6a6370>,
```

I looked into the knime.log and found this more detailed error:

```
2023-02-01 13:32:59,992 : ERROR : KNIME-Worker-72 : %J : Python Script (1⇒1) : Python Script (1⇒1) : 0:413:406:349 : Execute failed: Traceback (most recent call last):
  File "/Applications/KNIME 3.3.1.app/Contents/Eclipse/plugins/org.knime.python_3.3.0.v201611242050/py/PythonKernel.py", line 282, in execute
    exec(source_code, _exec_env, _exec_env)
  File "<string>", line 172, in <module>
  File "<string>", line 157, in extractfeaturepeaksfromsample
  File "<string>", line 56, in fillms1data
  File "pyopenms/pyopenms_7.pyx", line 2182, in pyopenms.pyopenms_7.ChromatogramExtractorAlgorithm.extractChromatograms (pyopenms/pyopenms_7.cpp:59525)
Exception: can not handle type of (<pyopenms.pyopenms_8.SpectrumAccessOpenMS object at 0x7fdeec6a6f70>, [<pyopenms.pyopenms_5.OSChromatogram object at 0x7fdeec6a6fb0>, <pyopenms.pyopenms_5.OSChromatogram object at 0x7fdeec6a6a70>, <pyopenms.pyopenms_5.OSChromatogram object at 0x7fdeec6a6ef0>, <pyopenms.pyopenms_5.OSChromatogram object at 0x7fdeec6a6cd0>, <pyopenms.pyopenms_5.OSChromatogram object at 0x7fdeec6a6d90>, 
``` 

Any suggestion of how to fix this would be greatly appreciated.

Thank you,
Faith
<img width="782" alt="Screenshot 2023-02-01 at 1 33 54 PM" src="https://user-images.githubusercontent.com/36000246/216148457-eb453e5e-9de8-461b-8e20-6ac32c134c6e.png">

**Comment by lfnothias** [comment]
Hi Faith,
Optimus is not supported anymore. The recommended was to do molecular cartography is to use any of feature-based molecular networking software (like MZmine) and run ili via a job on GNPS https://ccms-ucsd.github.io/GNPSDocumentation/metadata/#requirements-specific-to-ili
https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/

Best,

LFX
